import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head"; // Import Head from next/head
import React from "react"; // Import React for type definitions

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // Ensure children prop is defined here
}: {
  children: React.ReactNode; // Define the type of children
}) {
  return (
    <html lang="en">
      <Head>
        {/* Add any other meta tags or head elements here */}
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children} {/* Render the children here */}
        {/* Matomo Tracking Code */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              var _paq = window._paq = window._paq || [];
              _paq.push(['trackPageView']);
              _paq.push(['enableLinkTracking']);
              (function() {
                var u="https://webanalyticstesting2024.matomo.cloud/";
                _paq.push(['setTrackerUrl', u+'matomo.php']);
                _paq.push(['setSiteId', '1']);
                var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
                g.async=true; g.src='https://cdn.matomo.cloud/webanalyticstesting2024.matomo.cloud/matomo.js'; 
                s.parentNode.insertBefore(g,s);
              })();
            `,
          }}
        />
        {/* End Matomo Code */}
      </body>
    </html>
  );
}
